# Use postgres/example user/password credentials
version: '3.8'
services:
  pedidos:
    image: postgres:12.3
    volumes:
      - ~/volumes/postgres/pedidos/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pedidos
      - POSTGRES_PASSWORD=root
    ports:
      - 127.0.0.1:5433:5432