server:
  port: 0
spring:
  application:
    name: pagamentos-ms
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: liquibase/master.xml
eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka